version: '3.8'

services:
  # 1. Pagila Database Container
  postgres-pagila:
    image: postgres:15
    container_name: postgres-pagila
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    command: postgres -c listen_addresses='*'
    ports:
      - "5434:5432" 

  # 2. Sakila Database Container
  postgres-sakila:
    image: postgres:15
    container_name: postgres-sakila
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    command: postgres -c listen_addresses='*'
    ports:
      - "5433:5432" 

  # 3. Apache Airflow Container
  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow-standalone
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-snowflake
    volumes:
      - airflow-data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
    command: standalone
    ports:
      - "8080:8080"
    depends_on:
      - postgres-pagila
      - postgres-sakila

volumes:
  airflow-data: